# Generated by Django 3.1.3 on 2020-11-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productosVenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosventa',
            name='tamaño',
            field=models.CharField(default=None, max_length=7),
        ),
        migrations.AlterField(
            model_name='productosventa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
