# Generated by Django 3.1.3 on 2020-11-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productosVenta', '0002_auto_20201116_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosventa',
            name='talle',
            field=models.CharField(default=None, max_length=7),
        ),
    ]
