# Generated by Django 3.1.3 on 2020-11-29 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CategoriaIndumentaria', '0001_initial'),
        ('productosVenta', '0003_productosventa_talle'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosventa',
            name='CatIndumentaria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CategoriaIndumentaria.categoriaindumentaria'),
        ),
    ]
