# Generated by Django 3.1.3 on 2020-11-29 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('tel', models.IntegerField(max_length=12)),
                ('dni', models.IntegerField(max_length=8)),
                ('curso', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='curso.cursomodels')),
            ],
        ),
    ]
